### ISSUE TITLE
Optional M2 config keys are mandatory

### ISSUE THREAD

**Issue by adragus-inviqa** [tkotosz/behat-magento2-init#2]
Readme says:

```
      magento_configs:
        -
          path: 'admin/security/use_form_key'
          value: 0
```

But `\Bex\Behat\Magento2InitExtension\Fixtures\MagentoConfigManager::isValidConfig()` will fail every config which doesn't have **all** the keys defined - including `scope_type` and `scope_code`. I see no defaults set to them when they don't exist.
